import { type Node, type Edge } from '@xyflow/react';
import type { VibefulNodeData } from './flowStore';
import { VIBEFUL_NODE_TYPES } from '../const';
import { load as yamlLoad } from 'js-yaml';

/** Generates a Vibeful-compatible agent graph YAML config. */
export function generateYaml(
  nodes: Node<VibefulNodeData>[],
  edges: Edge[],
  agentName: string,
  agentDescription: string,
  analysisConfig?: Record<string, unknown>
): string {
  const lines: string[] = [];

  // ── Agent metadata ──
  lines.push(`# Generated by Vibeful Management Console`);
  lines.push(`name: ${agentName || 'Untitled Agent'}`);
  if (agentDescription) lines.push(`description: ${agentDescription}`);
  lines.push(`model: deepseek-chat`);
  lines.push(`temperature: 0.7`);
  lines.push(`top_p: 1.0`);
  lines.push(`max_tokens: 4096`);
  lines.push('');

  // ── Graph ──
  lines.push('graph:');
  const entryNode = nodes[0];
  lines.push(`  entry: ${entryNode?.data?.label?.toLowerCase().replace(/\s+/g, '_') || 'setup'}`);
  lines.push('  nodes:');

  for (const node of nodes) {
    const nodeName = node.data.label.toLowerCase().replace(/\s+/g, '_');
    const nodeTypeInfo = VIBEFUL_NODE_TYPES.find((nt) => nt.type === node.data.nodeType);

    lines.push(`    - name: ${nodeName}`);
    lines.push(`      type: ${node.data.nodeType}`);

    // Add config block if node has configuration
    if (nodeTypeInfo?.configSchema && Object.keys(node.data.config).length > 0) {
      lines.push('      config:');
      for (const [key, value] of Object.entries(node.data.config)) {
        if (typeof value === 'number') {
          lines.push(`        ${key}: ${value}`);
        } else if (typeof value === 'string') {
          lines.push(`        ${key}: ${JSON.stringify(value)}`);
        } else {
          lines.push(`        ${key}: ${JSON.stringify(value)}`);
        }
      }
    }
    // Include default config if no user config set
    else if (nodeTypeInfo?.defaultConfig) {
      lines.push('      config:');
      for (const [key, value] of Object.entries(nodeTypeInfo.defaultConfig)) {
        if (typeof value === 'number') {
          lines.push(`        ${key}: ${value}`);
        } else {
          lines.push(`        ${key}: ${JSON.stringify(value)}`);
        }
      }
    }
  }

  // ── Edges ──
  lines.push('  edges:');
  for (const edge of edges) {
    const sourceNode = nodes.find((n) => n.id === edge.source);
    const targetNode = nodes.find((n) => n.id === edge.target);
    const sourceName = sourceNode?.data?.label?.toLowerCase().replace(/\s+/g, '_') || 'unknown';
    const targetName = targetNode?.data?.label?.toLowerCase().replace(/\s+/g, '_') || 'unknown';

    // Handle attack_guard special case (conditional edge with safe/end)
    if (sourceNode?.data?.nodeType === 'builtin.attack_guard') {
      lines.push(`    - from: ${sourceName}`);
      lines.push('      routes:');
      lines.push(`        safe: ${targetName}`);
    }
    // Handle router special case (conditional edge)
    else if (sourceNode?.data?.nodeType === 'builtin.router') {
      lines.push(`    - from: ${sourceName}`);
      lines.push('      routes:');
      lines.push(`        rag: rag`);
      lines.push(`        react_agent: ${targetName}`);
      lines.push(`        mcp_discovery: mcp_discovery`);
    }
    // Last node before END
    else if (!edges.some((e) => e.source === edge.target)) {
      lines.push(`    - from: ${sourceName}`);
      lines.push(`      to: ${targetName}`);
      lines.push(`    - from: ${targetName}`);
      lines.push('      to: __END__');
    }
    else {
      lines.push(`    - from: ${sourceName}`);
      lines.push(`      to: ${targetName}`);
    }
  }

  // ── Analysis config ──
  if (analysisConfig) {
    lines.push('');
    lines.push('analysis:');
    lines.push(`  enabled: true`);
    lines.push('  phases:');
    for (const [phaseName, phaseCfg] of Object.entries(analysisConfig)) {
      const cfg = phaseCfg as { enabled: boolean; temperature?: number };
      lines.push(`    ${phaseName}:`);
      lines.push(`      enabled: ${cfg.enabled}`);
      if (cfg.temperature !== undefined) {
        lines.push(`      temperature: ${cfg.temperature}`);
      }
    }
  }

  return lines.join('\n');
}

/** Parse API response agent config back to nodes/edges for the flow canvas. */
export function parseGraphFromYaml(
  config: Record<string, unknown>
): { nodes: Node<VibefulNodeData>[]; edges: Edge[] } | null {
  try {
    // The API returns agents with config_json (a YAML string). Parse that first.
    const yamlStr = (config as any).config_json || (config as any).config_yaml;
    const parsed = yamlStr ? (typeof yamlStr === 'string' ? yamlLoad(yamlStr) : yamlStr) : config;
    const graphConfig = (parsed as any).graph || (config as any).graph;
    if (!graphConfig?.nodes) return null;

    const nodes: Node<VibefulNodeData>[] = [];
    const edges: Edge[] = [];
    let y = 50;

    for (const nodeDef of graphConfig.nodes) {
      const nodeName = nodeDef.name || 'unnamed';
      const nodeType = nodeDef.type || 'builtin.setup';
      const nodeConfig = nodeDef.config || {};

      nodes.push({
        id: `imported_${nodes.length}`,
        type: 'vibefulNode',
        position: { x: 250, y },
        data: {
          label: nodeName,
          nodeType,
          config: nodeConfig,
        },
      });
      y += 120;
    }

    // Build edges from config
    if (graphConfig.edges) {
      for (const edgeDef of graphConfig.edges) {
        const fromName = edgeDef.from;
        const toName = edgeDef.to;
        const routes = edgeDef.routes;

        const fromNode = nodes.find((n) => n.data.label === fromName);
        if (!fromNode) continue;

        if (routes) {
          for (const [routeLabel, targetLabel] of Object.entries(routes)) {
            const targetNode = nodes.find((n) => n.data.label === targetLabel);
            if (targetNode && targetLabel !== '__END__') {
              edges.push({
                id: `imported_edge_${fromNode.id}_${targetNode.id}_${routeLabel}`,
                source: fromNode.id,
                target: targetNode.id,
                label: routeLabel,
              });
            }
          }
        } else if (toName && toName !== '__END__') {
          const targetNode = nodes.find((n) => n.data.label === toName);
          if (targetNode) {
            edges.push({
              id: `imported_edge_${fromNode.id}_${targetNode.id}`,
              source: fromNode.id,
              target: targetNode.id,
            });
          }
        }
      }
    }

    return { nodes, edges };
  } catch {
    return null;
  }
}
