"""Agent CRUD invariants — guard against regressions in create/update/delete.

Invariants tested:
- updated_at is present and non-null on create
- updated_at changes on any update (name, styling, config)
- created_at never changes on update
- Partial put with empty config_yaml preserves existing config
- Agent round-trip survives full 15-node graph
"""

from __future__ import annotations

import httpx
import pytest
import yaml
import time


BASE = "http://127.0.0.1:50052"


# ═══════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════

def _create_agent(name: str, config_yaml: str = "", **kwargs) -> dict:
    body = {"name": name, "description": "", "system_prompt": "", "config_yaml": config_yaml, **kwargs}
    r = httpx.post(f"{BASE}/v1/agents", json=body)
    assert r.status_code == 200, f"Create failed: {r.text}"
    return r.json()


def _get_agent(agent_id: str) -> dict:
    r = httpx.get(f"{BASE}/v1/agents/{agent_id}")
    assert r.status_code == 200, f"Get failed: {r.text}"
    return r.json()


def _delete_agent(agent_id: str):
    r = httpx.delete(f"{BASE}/v1/agents/{agent_id}")
    assert r.status_code in (200, 404)


def _put_agent(agent_id: str, **kwargs) -> dict:
    r = httpx.put(f"{BASE}/v1/agents/{agent_id}", json=kwargs)
    assert r.status_code == 200, f"PUT failed: {r.text}"
    return r.json()


MINIMAL_YAML = """# Test YAML
name: test-agent
model: deepseek-chat

graph:
  entry: setup
  nodes:
    - name: setup
      type: builtin.setup
  edges:
    - from: setup
      to: __END__
"""

FULL_15_NODE_YAML = """# Generated by Vibeful Management Console
name: full-graph-test
model: deepseek-chat
temperature: 0.7

graph:
  entry: attack_guard
  nodes:
    - name: attack_guard
      type: builtin.attack_guard
    - name: setup
      type: builtin.setup
    - name: fact_recall
      type: builtin.fact_recall
    - name: planning
      type: builtin.planning
    - name: buttons
      type: builtin.buttons
    - name: system_message_builder
      type: builtin.system_message_builder
    - name: analysis_pipeline
      type: builtin.analysis_pipeline
    - name: rag
      type: builtin.rag
    - name: mcp_discovery
      type: builtin.mcp_discovery
    - name: react_agent
      type: builtin.react_agent
      config:
        max_iterations: 5
    - name: output_router
      type: builtin.output_router
    - name: stream_completion
      type: builtin.stream_completion
    - name: citation
      type: builtin.citation
    - name: follow_up
      type: builtin.follow_up
    - name: fact_mining
      type: builtin.fact_mining
  edges:
    - from: attack_guard
      routes:
        safe: setup
    - from: setup
      to: fact_recall
    - from: fact_recall
      to: planning
    - from: planning
      to: buttons
    - from: buttons
      to: system_message_builder
    - from: system_message_builder
      to: analysis_pipeline
    - from: analysis_pipeline
      to: rag
    - from: analysis_pipeline
      to: react_agent
    - from: analysis_pipeline
      to: mcp_discovery
    - from: rag
      to: mcp_discovery
    - from: mcp_discovery
      to: react_agent
    - from: react_agent
      to: output_router
    - from: output_router
      to: stream_completion
    - from: stream_completion
      to: citation
    - from: citation
      to: follow_up
    - from: follow_up
      to: fact_mining
    - from: fact_mining
      to: __END__
"""


# ═══════════════════════════════════════════════════════════════
# Invariant: timestamps present and sensible
# ═══════════════════════════════════════════════════════════════

class TestAgentTimestamps:
    """Every agent must have valid created_at and updated_at timestamps."""

    def test_created_at_present_on_create(self):
        agent = _create_agent("ts-create-test", config_yaml=MINIMAL_YAML)
        try:
            assert "created_at" in agent, "created_at missing from create response"
            assert agent["created_at"], "created_at is empty/null"
        finally:
            _delete_agent(agent["id"])

    def test_updated_at_present_on_create(self):
        agent = _create_agent("ts-update-create", config_yaml=MINIMAL_YAML)
        try:
            assert "updated_at" in agent, "updated_at missing from create response"
            assert agent["updated_at"], "updated_at is empty/null"
        finally:
            _delete_agent(agent["id"])

    def test_updated_at_present_on_get(self):
        agent = _create_agent("ts-get-test", config_yaml=MINIMAL_YAML)
        try:
            reloaded = _get_agent(agent["id"])
            assert "updated_at" in reloaded, "updated_at missing from GET response"
            assert reloaded["updated_at"], "updated_at is empty/null on GET"
        finally:
            _delete_agent(agent["id"])

    def test_updated_at_changes_on_name_update(self):
        agent = _create_agent("ts-name-update", config_yaml=MINIMAL_YAML)
        try:
            original = agent["updated_at"]
            time.sleep(1.1)  # ensure timestamp difference
            _put_agent(agent["id"], name="ts-name-updated")
            reloaded = _get_agent(agent["id"])
            assert reloaded["updated_at"] != original, (
                f"updated_at didn't change after name update: {original} → {reloaded['updated_at']}"
            )
        finally:
            _delete_agent(agent["id"])

    def test_updated_at_changes_on_styling_update(self):
        agent = _create_agent("ts-style-update", config_yaml=MINIMAL_YAML, styling="light")
        try:
            original = agent["updated_at"]
            time.sleep(1.1)
            _put_agent(agent["id"], styling="dark")
            reloaded = _get_agent(agent["id"])
            assert reloaded["updated_at"] != original, (
                f"updated_at didn't change after styling update"
            )
        finally:
            _delete_agent(agent["id"])

    def test_updated_at_changes_on_config_update(self):
        agent = _create_agent("ts-config-update", config_yaml=MINIMAL_YAML)
        try:
            original = agent["updated_at"]
            time.sleep(1.1)
            _put_agent(agent["id"], config_yaml=FULL_15_NODE_YAML)
            reloaded = _get_agent(agent["id"])
            assert reloaded["updated_at"] != original, (
                f"updated_at didn't change after config update"
            )
        finally:
            _delete_agent(agent["id"])

    def test_created_at_never_changes(self):
        agent = _create_agent("ts-created-immutable", config_yaml=MINIMAL_YAML)
        try:
            original_created = agent["created_at"]
            _put_agent(agent["id"], name="ts-created-renamed")
            _put_agent(agent["id"], styling="brand")
            reloaded = _get_agent(agent["id"])
            assert reloaded["created_at"] == original_created, (
                f"created_at changed! was {original_created}, now {reloaded['created_at']}"
            )
        finally:
            _delete_agent(agent["id"])


# ═══════════════════════════════════════════════════════════════
# Invariant: empty config doesn't corrupt existing
# ═══════════════════════════════════════════════════════════════

class TestEmptyConfigGuard:
    """PUT with empty or missing config_yaml must not wipe existing config."""

    def test_put_without_config_preserves_existing(self):
        agent = _create_agent("empty-guard-test", config_yaml=MINIMAL_YAML)
        try:
            _put_agent(agent["id"], name="renamed-no-config")
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            assert len(yaml_field) > 10, "Existing config_yaml was wiped"
            parsed = yaml.safe_load(yaml_field)
            assert parsed is not None
            nodes = parsed.get("graph", {}).get("nodes", [])
            assert len(nodes) > 0, "graph.nodes were wiped"
        finally:
            _delete_agent(agent["id"])

    def test_put_with_empty_string_config_preserves_existing(self):
        agent = _create_agent("empty-str-guard-test", config_yaml=MINIMAL_YAML)
        try:
            _put_agent(agent["id"], config_yaml="")
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            assert len(yaml_field) > 10, "Config was wiped by empty string PUT"
        finally:
            _delete_agent(agent["id"])


# ═══════════════════════════════════════════════════════════════
# Invariant: full 15-node graph survives round-trip
# ═══════════════════════════════════════════════════════════════

class TestFullGraphRoundTrip:
    """A full 15-node graph must survive create → read → nodes intact."""

    def test_full_graph_node_count(self):
        agent = _create_agent("fullgraph-count", config_yaml=FULL_15_NODE_YAML)
        try:
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            parsed = yaml.safe_load(yaml_field)
            nodes = parsed["graph"]["nodes"]
            assert len(nodes) == 15, f"Expected 15 nodes, got {len(nodes)}"
        finally:
            _delete_agent(agent["id"])

    def test_full_graph_all_node_names(self):
        agent = _create_agent("fullgraph-names", config_yaml=FULL_15_NODE_YAML)
        try:
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            parsed = yaml.safe_load(yaml_field)
            node_names = {n["name"] for n in parsed["graph"]["nodes"]}
            expected = {
                "attack_guard", "setup", "fact_recall", "planning", "buttons",
                "system_message_builder", "analysis_pipeline", "rag", "mcp_discovery",
                "react_agent", "output_router", "stream_completion", "citation",
                "follow_up", "fact_mining",
            }
            missing = expected - node_names
            assert not missing, f"Missing nodes: {missing}"
        finally:
            _delete_agent(agent["id"])

    def test_full_graph_survives_update(self):
        agent = _create_agent("fullgraph-update", config_yaml=MINIMAL_YAML)
        try:
            _put_agent(agent["id"], config_yaml=FULL_15_NODE_YAML)
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            parsed = yaml.safe_load(yaml_field)
            assert len(parsed["graph"]["nodes"]) == 15
        finally:
            _delete_agent(agent["id"])

    def test_full_graph_edges_intact(self):
        agent = _create_agent("fullgraph-edges", config_yaml=FULL_15_NODE_YAML)
        try:
            reloaded = _get_agent(agent["id"])
            yaml_field = reloaded.get("config_json") or reloaded.get("config_yaml") or ""
            parsed = yaml.safe_load(yaml_field)
            edges = parsed["graph"]["edges"]
            assert len(edges) == 17, f"Expected 17 edges, got {len(edges)}"
        finally:
            _delete_agent(agent["id"])
